import type { ConnectorCatalogItem, ConnectorCategory } from "./schemas";

/** Static catalog — safe to import from client components. */
export const CONNECTOR_CATALOG: ConnectorCatalogItem[] = [
  {
    id: "gmail",
    name: "Gmail",
    description: "Read and search email, draft replies, and triage your inbox from agents.",
    category: "communication",
    authType: "oauth2",
    icon: "mail",
    envKey: "",
    oauthProvider: "google",
    docsUrl: "https://developers.google.com/gmail/api",
    configurable: false,
  },
  {
    id: "google-calendar",
    name: "Google Calendar",
    description: "View events, check availability, and schedule meetings in your workspace context.",
    category: "productivity",
    authType: "oauth2",
    icon: "calendar",
    envKey: "",
    oauthProvider: "google",
    docsUrl: "https://developers.google.com/calendar",
    configurable: false,
  },
  {
    id: "outlook",
    name: "Outlook",
    description: "Microsoft 365 mail and calendar via Microsoft Graph.",
    category: "productivity",
    authType: "oauth2",
    icon: "outlook",
    envKey: "",
    docsUrl: "https://learn.microsoft.com/graph/",
    configurable: false,
  },
  {
    id: "slack",
    name: "Slack",
    description: "Post messages, read channels, and route agent updates to your team.",
    category: "communication",
    authType: "oauth2",
    icon: "slack",
    envKey: "",
    docsUrl: "https://api.slack.com/",
    configurable: false,
  },
  {
    id: "discord",
    name: "Discord",
    description: "Connect your bot to send and read messages in selected channels.",
    category: "communication",
    authType: "api_key",
    icon: "discord",
    envKey: "Sebastian_Discord_Bot_Key",
    docsUrl: "https://discord.com/developers/docs",
    configurable: false,
  },
  {
    id: "imessage",
    name: "iMessage",
    description: "Local macOS bridge for sending and reading messages (experimental).",
    category: "communication",
    authType: "local",
    icon: "message",
    envKey: "",
    configurable: false,
  },
  {
    id: "mcp-higgsfield",
    name: "Higgsfield",
    description: "MCP server for Higgsfield media and generation workflows.",
    category: "creative",
    authType: "mcp",
    icon: "sparkles",
    envKey: "",
    configurable: true,
  },
  {
    id: "mcp-meshy",
    name: "Meshy",
    description: "MCP server for Meshy 3D generation and asset pipelines.",
    category: "creative",
    authType: "mcp",
    icon: "box",
    envKey: "",
    configurable: true,
  },
  {
    id: "mcp-custom",
    name: "Custom MCP Server",
    description: "Add any MCP-compatible server by URL — tools become available to agents in this workspace.",
    category: "mcp",
    authType: "mcp",
    icon: "plug",
    envKey: "",
    configurable: true,
  },
];

export const CATEGORY_ORDER: ConnectorCategory[] = ["communication", "productivity", "creative", "mcp"];

export const CATEGORY_LABELS: Record<ConnectorCategory, string> = {
  communication: "Communication",
  productivity: "Productivity",
  creative: "Creative",
  mcp: "MCP Servers",
};
